media_folder: my-site/src/assets/images
public_folder: /assets/images

content:
  # Blog Posts Collection
  - name: posts
    label: Posts
    type: collection
    path: my-site/src/pages/posts
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: body
        label: Body
        type: rich-text

  # Site-wide Settings (simplified - just the basics that work)
  - name: site-settings
    label: Site Settings
    type: file
    path: my-site/src/data/siteContent.json
    fields:
      - name: meta_title
        label: Site Title
        type: string
        description: Main site title (appears in browser tab)
      - name: meta_description
        label: Site Description
        type: string
        description: Brief description for SEO
      - name: header
        label: Header
        type: object
        fields:
          - name: logo_text
            label: Logo Text
            type: string
            description: Text that appears in the header/logo area
      - name: footer
        label: Footer
        type: object
        fields:
          - name: text
            label: Footer Text
            type: string
            description: Copyright text in footer

  # Individual Pages
  - name: pages
    label: Pages
    type: collection
    path: my-site/src
    extension: md
    fields:
      - name: title
        label: Title
        type: string
      - name: layout
        label: Layout
        type: string
        default: base
      - name: body
        label: Body
        type: rich-text
