media_folder: my-site/src/assets/images
public_folder: /assets/images

content:
  # Blog Posts Collection
  - name: posts
    label: Posts
    type: collection
    path: my-site/src/pages/posts
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: body
        label: Body
        type: rich-text

  # Site-wide Settings - NOW WITH WORKING MENUS!
  - name: site-settings
    label: Site Settings
    type: file
    path: my-site/src/data/siteContent.json
    fields:
      - name: meta_title
        label: Site Title
        type: string
        description: Main site title (appears in browser tab)
      
      - name: meta_description
        label: Site Description
        type: string
        description: Brief description for SEO
      
      - name: header
        label: Header
        type: object
        fields:
          - name: logo_text
            label: Logo Text
            type: string
            description: Text that appears in the header/logo area
          
          - name: nav_links
            label: Navigation Menu Items
            type: object
            list: true
            fields:
              - name: text
                label: Menu Text
                type: string
              - name: href
                label: Link URL
                type: string
      
      - name: sidebar
        label: Sidebar
        type: object
        fields:
          - name: categories
            label: Categories
            type: object
            list: true
            fields:
              - name: name
                label: Category Name
                type: string
              - name: link
                label: Category URL
                type: string
      
      - name: footer
        label: Footer
        type: object
        fields:
          - name: text
            label: Footer Text
            type: string

  # Individual Pages
  - name: pages
    label: Pages
    type: collection
    path: my-site/src
    extension: md
    fields:
      - name: title
        label: Title
        type: string
      - name: layout
        label: Layout
        type: string
        default: base
      - name: body
        label: Body
        type: rich-text
