media_folder: my-site/src/assets/images
public_folder: /assets/images

content:
  - name: posts
    label: Posts
    type: collection
    path: my-site/src/pages/posts
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: body
        label: Body
        type: rich-text
